// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT19TFPv_cTft6L6Kj_uVQdGCi5tv9d9Q',
    appId: '1:218738781112:web:c810365442c3d478e93d4d',
    messagingSenderId: '218738781112',
    projectId: 'walmart-b2b',
    authDomain: 'walmart-b2b.firebaseapp.com',
    storageBucket: 'walmart-b2b.firebasestorage.app',
    measurementId: 'G-T52RSRCPYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx-VbSotnKfVyBGhiCWYA8Ox1UdQEDcmQ',
    appId: '1:218738781112:android:d590af7f366a45cae93d4d',
    messagingSenderId: '218738781112',
    projectId: 'walmart-b2b',
    storageBucket: 'walmart-b2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNtZeVbpiG7QloHQcr3_fnlMxQrkhh0XM',
    appId: '1:218738781112:ios:a4234557576e25d0e93d4d',
    messagingSenderId: '218738781112',
    projectId: 'walmart-b2b',
    storageBucket: 'walmart-b2b.firebasestorage.app',
    iosBundleId: 'com.example.walmartB2bApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNtZeVbpiG7QloHQcr3_fnlMxQrkhh0XM',
    appId: '1:218738781112:ios:a4234557576e25d0e93d4d',
    messagingSenderId: '218738781112',
    projectId: 'walmart-b2b',
    storageBucket: 'walmart-b2b.firebasestorage.app',
    iosBundleId: 'com.example.walmartB2bApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT19TFPv_cTft6L6Kj_uVQdGCi5tv9d9Q',
    appId: '1:218738781112:web:9bb332a6db4990b9e93d4d',
    messagingSenderId: '218738781112',
    projectId: 'walmart-b2b',
    authDomain: 'walmart-b2b.firebaseapp.com',
    storageBucket: 'walmart-b2b.firebasestorage.app',
    measurementId: 'G-L6NLJXCP6R',
  );
}
